### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by gillchristian** [ndelvalle/rustdis#8]
## Milestones

1. Make it public (**2024-04-23**) ✅ 
1. Support string commands (without options) [/commands/?group=string](https://redis.io/docs/latest/commands/?group=string) & [/data-types/strings/](https://redis.io/docs/latest/develop/data-types/strings/) (**2024-05-05**) ✅
    - https://github.com/ndelvalle/rustdis/milestone/1
    - #30
1. Document it (README, notes, comments, _et al_)
    - https://github.com/ndelvalle/rustdis/milestone/2 
1. Server improvements (TTL, client info, etc)
    - https://github.com/ndelvalle/rustdis/milestone/3
1. Future milestones
    1. Persist to disk & "log file" ([Redis persistence](https://redis.io/docs/latest/operate/oss_and_stack/management/persistence/))
    1. Compatibility test suit
    3. String commands with all options

## TO-DO

- [ ] Does the protocol ever send `-1` on the bulk error?
- [x] Change the store type to keep information about the key (eg. ttl) @gillchristian 
- [ ] Keep a record of connected clients. For `client` commands. @gillchristian 
- [x] TTL
- [ ] Validate argument count:
    ```
    redis> PING hello world
    (error) wrong number of arguments for 'ping' command
    ```
- [x] All string commands [/commands/?group=string](https://redis.io/docs/latest/commands/?group=string) & [/data-types/strings/](https://redis.io/docs/latest/develop/data-types/strings/)
- [ ] Bulk frames (string / error) could be optimized by reading the specified `length`
- [x] Documentation and notes ([ferrum-field.vercel.app](https://ferrum-field.vercel.app/))
- [x] Implement logging
- [x] Nested commands (eg.`object encoding`, `object freq`)
